services:
    client:
        depends_on:
            - server
        image: client
        container_name: sboard-client
        build:
            context: ./client
            dockerfile: Dockerfile         
        networks:
            - main
        ports:
            - 3000:3000
        command: [ "node", "server.js" ]
    server:
        depends_on:
            - postgres
        image: server
        container_name: sboard-server
        build:
            context: ./server
            dockerfile: Dockerfile
        networks:
            - main
        ports:
            - 5000:5000
        env_file:
            - .env
        command: [ "node", "./dist/src/main.js" ]
    postgres:
        image: postgres:17-alpine
        container_name: postgres
        networks:
            - main
        restart: unless-stopped
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: app_db
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
    main: