FROM node:20.18.1-alpine AS server
WORKDIR /app
ADD *.json .
RUN npm ci
ADD . .
RUN npm run build


FROM node:20.18.1-alpine
WORKDIR /app
COPY --from=server /app/dist ./dist
ADD *.json .
RUN npm ci --omit=dev